### Login to the system
POST {{base_url}}/auth/login HTTP/1.1
X-Tenant: ivms-api.vienthongtayninh.vn
Content-Type: application/json

{
  "username": "starcom",
  "password": "12345678aA@"
}

### Synchronize privileges
POST {{base_url}}/privileges/sync HTTP/1.1
Authorization: Bearer {{access_token}}

### Logout from the system
POST {{base_url}}/auth/logout HTTP/1.1
Authorization: Bearer {{access_token}}

### Refresh the access token
POST {{base_url}}/auth/refresh-token HTTP/1.1
Authorization: Bearer {{refresh_token}}

### Register a new user
POST {{base_url}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "username": "string",
  "password": "string",
  "first_name": "string",
  "last_name": "string",
  "full_name": "string",
  "phone": "string",
  "email": "string",
  "avatar_url": "string",
  "idn": "string",
  "ial": 0
}